export {
  authorize,
  can,
  computeEffectivePermissions,
  defineAccessControl,
  isPermission,
  listPermissionGroups,
  listPermissions,
  partitionPermissionGrants,
  roleAtLeast,
  type AccessControlDefinition,
  type AccessControlModel,
  type AuthorizeOptions,
  type AuthorizeResult,
  type EffectivePermissionInput,
  type Permission,
  type PermissionGrant,
  type PermissionGroup,
  type PermissionMeta,
  type Role,
} from "./access-control.js";
export {
  buildWorkspaceEntityIndex,
  collectEntityOwners,
  entityMentionId,
  filterWorkspaceEntities,
  findEntityByMentionId,
  findEntityReferences,
  type WorkspaceEntityContribution,
  type WorkspaceEntityCorpusEntry,
  type WorkspaceEntityIndex,
  type WorkspaceEntityKind,
  type WorkspaceEntityQuery,
  type WorkspaceEntityRef,
  type WorkspaceEntitySource,
} from "./entities.js";
export {
  AI_ATTRIBUTION_MAX_LENGTH,
  normalizeAiAttribution,
  type AiAttribution,
} from "./provenance.js";
export {
  ShellHost,
  createPlatformCommandSource,
  type ActiveShellApp,
  type MicroAppRoute,
  type ShellAppActivationContext,
  type ShellAppInstance,
  type ShellAppManifest,
  type ShellAppModule,
  type ShellAppRenderProps,
  type ShellFeatureContribution,
  type ShellHostOptions,
  type ShellPreferenceDefault,
  type ShellSideNavMountContribution,
  type ShellTopNavMountArea,
  type ShellTopNavMountContribution,
  type WorkspaceContext,
} from "./host.js";
export {
  buildImportMapFromHost,
  buildShellImportMap,
  installShellImportMap,
  sharedImportPins,
  shellImportMapId,
  type ShellImportMap,
} from "./importmap.js";
export {
  CommandRegistry,
  ContextKeyService,
  DisposableStore,
  EventBus,
  PreferenceSnapshot,
  PreferencesStore,
  assertSingleShellInstance,
  configureShell,
  createShellSDK,
  resetShellForTests,
  resolvePreference,
  shell,
  type CommandContribution,
  type CommandEntity,
  type CommandExecutionContext,
  type CommandHandler,
  type CommandHistoryEntry,
  type CommandKind,
  type CommandPrefixMode,
  type CommandRing,
  type CommandShortcut,
  type CommandSourceContribution,
  type CommandVisibility,
  type ContextSnapshot,
  type ContextValue,
  type Disposable,
  type PreferenceInspection,
  type PreferenceOption,
  type PreferenceRing,
  type PreferenceSchema,
  type PreferenceScope,
  type PreferenceSource,
  type PreferenceValue,
  type PreferenceValueLayer,
  type PreferenceValueRecord,
  type RankedCommandResult,
  type ResolvedPreference,
  type RingContext,
  type SettingsGroup,
  type ShellEvent,
  type ShellSDK,
  type ShellSDKOptions,
} from "./shell-sdk.js";
